name: Deploy to Onamae RS (order-dev)

on:
  push:
    branches: [ "main", "dev" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: FTP deploy (order-page → /public_html/ping-pong-pang.jp/order-dev)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          protocol: ftps
          port: 21
          security: strict
          local-dir: ./order-page/                         # ← ローカルの中身だけ送る
          server-dir: public_html/ping-pong-pang.jp/order-dev/  # ← サーバの“絶対”パスに固定
          state-name: .ftp-state-order-dev.json
          dangerous-clean-slate: false
          exclude: |
            **/.git/**
            **/.github/**
            **/node_modules/**
            **/.DS_Store
            README*.md
            LICENSE
