name: Deploy to Onamae RS via FTPS (order-dev only)

on:
  push:
    branches: ["main", "dev"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy with FTP-Deploy-Action (FTPS strict)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}      # www1049.onamae.ne.jp
          username: ${{ secrets.FTP_USER }}    # ppp_ftp@ping-pong-pang.jp
          password: ${{ secrets.FTP_PASS }}
          protocol: ftps
          port: 21
          security: strict
          local-dir: ./
          server-dir: order-dev/
          log-level: verbose
          dangerous-clean-slate: false
          exclude: |
            **/.git/**
            **/.git*
            .git/**
            .git*
            **/.github/**
            **/node_modules/**
            **/*.map
            **/.DS_Store
            README*.md
            LICENSE
